version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/var/www/zonap/src
      - ./node_modules:/var/www/zonap/node_modules
    env_file: ./src/.env
    restart: on-failure
