version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/var/www/zonap/src
    env_file: ./source/.env
    restart: on-failure
